### PR TITLE
Delete search.start.fyi.png.source

### PR DESCRIPTION
**Pull request by sgiehl**
Source file on s3 does not exist any longer.

Seems the full search engine is actually offline meanwhile. 
Guess we can keep the icon nevertheless so it can be shown for older records.

### CODE REVIEW

**Comment by Findus23** [comment]
I am not sure why we need to delete the .source file. 
They are not used at run-time, but more of a note from me giving credit to where the image is from. 
So deleting it without also deleting the icon doesn't really do much.

**Comment by sgiehl** [comment]
It's pointing to an unexistent s3 bucket, that could be registered by someone else, who could then place another file there...

**Comment by Findus23** [comment]
But even then I am not sure what the issue would be. It's not like this URL is used for anything apart from knowing where the image is from. So we could just put a `(URL is no longer online)` in brackets afterwards.

**Comment by sgiehl** [comment]
I've removed the icon as well now.

**Pull request merged**
