### PR TITLE
brand/Danew

### PR DESCRIPTION
**Pull request by username1290**

### CODE REVIEW

**Comment by username1290** [comment]
btw added 1 pixel to make it square

**Comment by Findus23** [comment]
Hi,
Many thanks for adding a new icon. 🎉 
Just a few notes (as I haven't had time to write down how exactly I am structuring everything):
- As the text is often quite unreadable at small sizes () I often crop it away and just keep the characteristic symbol
- `square` is just a rule of thumb, as my converter script cuts all white space away and then places the icon on a square
- It would be really nice if you could add the exact URL to the file in the .source file.

**Comment by username1290** [comment]
👍

**Comment by Findus23** [comment]
Merged in #18

**Pull request closed without merging**
